FROM node:21.7-alpine AS build-stage
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:18-alpine AS frontend
WORKDIR /app
EXPOSE 8080
COPY --from=build-stage /app/build/ /app/build/
COPY --from=build-stage /app/package.json /app/package-lock.json /app/
RUN npm ci --omit dev 
CMD [ "node", "build" ]